### ISSUE TITLE
Enhancement: Remember paths

### ISSUE THREAD

**Issue by mcarans** [coozoo/qtjsondiff#11]
It would be great if the tool could optionally remember previous urls or paths to make it easier to repeat comparisons for example.

**Comment by coozoo** [comment]
Nice Idea. That's how small demo application becomes bigger.

I've added checkable button in main window. When checked it will load latest documents. And with next program open those urls or paths will be opened again.

Tell me is it good or did you mean something else?

Released new version

08511d4e8673d85459def392ec249b4750fd0af1

**Comment by mcarans** [comment]
Super, just like that! Thanks!

**Comment by mcarans** [comment]
Oh one thing is it would be great if it could remember which tab you were in (for example it should open in the Compare View if that was what was last being used).

**Comment by coozoo** [comment]
> Oh one thing is it would be great if it could remember which tab you were in (for example it should open in the Compare View if that was what was last being used).

Yeah I have the same thoughts :)
Done e7befed3229fa69a5036a5111c01988fcddfac74
