### ISSUE TITLE
Enhancement: Add selection of nodes and right click menu with expansion of nodes

### ISSUE THREAD

**Issue by mcarans** [coozoo/qtjsondiff#12]
It would be wonderful to be able to select nodes in the standard UI ways  - select all/none option, ctrl click on each, shift up/down arrow etc. then have a right click menu for the selected nodes with expand/collapse.

**Comment by coozoo** [comment]
It works in such way if you select more than one item you will see expand/collapse menu.
Old menu still will be appeared if only one item selected.
In diff mode selection will be reflected on existent items (in case when compare done), but if you need click manually from both sides to expand them.

**Comment by mcarans** [comment]
This is great  - the only thing is that it would be good to not just expand the node, but also its children nodes. Maybe there could be Expand and Expand Tree?

**Comment by coozoo** [comment]
I've added "Expand selected tree" menu item that will recursively expand them. And I didn't add such for collapse because actually I'm not sure that really such function required :)

**Comment by mcarans** [comment]
That's great! The expand selected tree option is also needed if you only select one node. As for collapsing a tree, I think it could be useful - it's always good to have the mirror function so a person can reverse what they did if it is in error without having to start over.

**Comment by coozoo** [comment]
ok, I've added collapse for the whole tree as well

3b8e5b69a4e5fb194e13637a5e581f33dc590804

**Comment by mcarans** [comment]
Super! Thanks a lot. The expand selected tree and collapse selected tree only work when you select 2 or more nodes, but I think that functionality is also needed when you only select one node.

**Comment by coozoo** [comment]
@mcarans yeah good point
669578047fb620c132996e708be120dd63d8cc7c
