### ISSUE TITLE
Compare button - coloured output not working

### ISSUE THREAD

**Issue by mcarans** [coozoo/qtjsondiff#24]
I'm not sure if this is the same issue as the alpha one, but in case not, the Compare button is not working properly having been broken in a recent update - non matching items show as green instead of red.

**Comment by coozoo** [comment]
you can try to uncheck "Use Full Path" if it's working then I think it's the same problem.
Try to get latest from https://github.com/coozoo/qtjsondiff/releases/tag/continuous
if you in rpm distro simply run `# dnf reinstall QTjsonDiff`

**Comment by mcarans** [comment]
Thanks, it is working after pulling latest version!
