### ISSUE TITLE
[discussion] ui re-layout to use window height more effectively

### ISSUE THREAD

**Issue by pvanek** [coozoo/qtjsondiff#26]
I just played with layouts a bit. I believe we can save some vertical space joining widgets into lines. Also it contains:

- compare button and sync checkboxes are in one line
- shortcut alt+c to run "compare"
- tabs are on the left. It's unusual and ugly, but I'm basically diff-only user and the vertical space is saved
- internally: the layouts are reduced dramatically: `6 files changed, 133 insertions(+), 198 deletions(-)` and there is still field to improve

![Screenshot_20201219_163857](https://user-images.githubusercontent.com/207237/102693156-c9f72e00-4218-11eb-9a3a-4afe7a17f67b.png)

**Comment by coozoo** [comment]
Actually everything sounds good even one line button with checkboxes.

But for me those tabs from left really looks weird and I'm not sure how they will look like on Mac.
And just today discovered that looks like no more free travi-ci builds, needs to find replacement.

**Comment by coozoo** [comment]
@pvanek I got some time and I have started layout reorder. 
Your layout looks nice but I've made just some moments that I don't like to be configurable. So in case of some small not wide monitor it is still possible to use app. 
Now tabs position in settings and button as well. 
If you able to branch out from this branch and merge your fixes it would be great :) 
thank you

**Comment by coozoo** [comment]
Tabs and show json button positions are configurable now. Applied some relayout
![image](https://user-images.githubusercontent.com/25594311/104792301-9b805a80-57a6-11eb-8cd5-eae3e7ceb78d.png)

**Comment by coozoo** [comment]
Closing it as I supposed it's enough. In case of disagree you can reopen :) or create new one
