### ISSUE TITLE
License

### ISSUE THREAD

**Issue by michalfapso** [coozoo/qtjsondiff#5]
Hi, I would like to use your project for commercial use, if such use is permitted. Could you please specify a license for your project?

Thank you.

**Comment by pali7no** [comment]
I 'd also like the answer to the same question as @michalfapso .

**Comment by coozoo** [comment]
c659ec6 

Just checked the license of original model project https://github.com/dridk/QJsonModel it is under MIT now to so decided to do the same.

**Comment by michalfapso** [comment]
Thanks a lot, Yuriy.
