### ISSUE TITLE
Does not run on Xubuntu 18.04

### ISSUE THREAD

**Issue by probonopd** [coozoo/qtjsondiff#6]
```
me@host:~$ Downloads/qtjsondiff-0.31b-Fedora29-e-x86_64.AppImage 
Downloads/qtjsondiff-0.31b-Fedora29-e-x86_64.AppImage: relocation error: /tmp/.mount_qtjsonVr8q0O/lib/libc.so.6: symbol _dl_starting_up version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

Please compile on Ubuntu xenial. Fedora 29 is too new.

**Comment by coozoo** [comment]
actually currently I'm on fedora 31..
maybe if i can find some ubuntu I can compile but not sure if I can find such. It shouldn't be a problem to compile it if at least QT5.11 available with this ubuntu.

**Comment by probonopd** [comment]
Thank you. It's always a good idea to build on a build machine that is different from a personal developer's computer. E.g., Travis CI lets you build on Ubuntu xenial easily. I will send a pull request.
