### ISSUE TITLE
Desktop file is missing

### ISSUE THREAD

**Issue by probonopd** [coozoo/qtjsondiff#7]
The `qtjsondiff.desktop` file is missing in this repository. It should be installed by `make install` just like the icon.

```
[Desktop Entry]
Type=Application
Categories=Development;
Name=qtjsondiff
Exec=qtjsondiff %F
Icon=diff
Comment=Qt JSON diff
```

**Comment by coozoo** [comment]
@probonopd 
sorry, do you mean that this files should go to `/usr/share/applications` ?

**Comment by coozoo** [comment]
@probonopd 
I've added something like this tell me if it's not what required
e67a363

**Comment by coozoo** [comment]
@probonopd thanks looks like it works
