### ISSUE TITLE
"make install" does not work

### ISSUE THREAD

**Issue by probonopd** [coozoo/qtjsondiff#8]
```
make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
make: Nothing to be done for 'install'.
```

**Comment by coozoo** [comment]
@probonopd do you mean something like this?
install.files += QTjsonDiff
install.path = /usr/local/qtjsondiff
INSTALLS += install

i'm asking about this path 
/usr/local/qtjsondiff 
or is it better? 
/usr/local/bin

thanks

**Comment by coozoo** [comment]
@probonopd 
install target has been added 4021f71
